# Generated by Django 5.2.5 on 2025-10-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_alter_coupon_options_remove_coupon_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='discount_type',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount amount in currency (e.g., 200.00)', max_digits=10),
        ),
    ]
