# Generated by Django 5.2.5 on 2025-10-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_remove_coupon_discount_type_and_more'),
        ('products', '0004_rename_body_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='products.product'),
        ),
    ]
