# Generated by Django 5.2.5 on 2025-10-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_coupon_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='products',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='users_used',
        ),
    ]
