# Generated by Django 5.2.5 on 2025-10-21 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_remove_coupon_products_remove_coupon_users_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='total_uses',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='usage_limit_per_user',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='usage_limit_total',
        ),
    ]
