# Generated by Django 5.2.5 on 2025-10-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0008_remove_coupon_total_uses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount to apply this coupon', max_digits=10),
        ),
    ]
