# Generated by Django 5.2.5 on 2025-10-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0009_coupon_min_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Maximum discount amount allowed for this coupon', max_digits=10),
        ),
        migrations.AddField(
            model_name='coupon',
            name='total_uses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
