# Generated by Django 5.2.5 on 2025-10-21 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0010_coupon_max_discount_amount_coupon_total_uses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='max_discount_amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='min_order_amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='total_uses',
        ),
    ]
