# Generated by Django 5.2.5 on 2025-11-04 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0012_alter_coupon_options_rename_active_coupon_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='maximum_discount_amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='minimum_order_amount',
        ),
    ]
