# Generated by Django 5.2.5 on 2025-09-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit'), ('Failed', 'Failed')], default='Pending', max_length=10),
        ),
    ]
