# Generated by Django 5.2.5 on 2025-08-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='profiles/'),
        ),
    ]
