# Generated by Django 5.2.5 on 2025-09-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_profile_email_otp_profile_otp_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='profile/'),
        ),
    ]
