# Generated by Django 5.2.5 on 2025-08-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_status_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancellation_approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cancellation_requested',
            field=models.BooleanField(default=False),
        ),
    ]
