# Generated by Django 5.2.5 on 2025-10-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_discount_orderitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
