# Generated by Django 5.2.5 on 2025-10-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='original_price',
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
