# Generated by Django 5.2.5 on 2025-10-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderitem_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_refunded',
            field=models.BooleanField(default=False),
        ),
    ]
