# Generated by Django 5.2.5 on 2025-08-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='refund_done',
            field=models.BooleanField(default=False),
        ),
    ]
