# Generated by Django 5.2.5 on 2025-11-04 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0012_alter_coupon_options_rename_active_coupon_is_active_and_more'),
        ('orders', '0013_order_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupons.coupon'),
        ),
    ]
