# Generated by Django 5.2.5 on 2025-09-20 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productoffer',
            name='unique_product_offer',
        ),
    ]
