# Generated by Django 5.2.5 on 2025-10-12 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_avg_rating_product_rating_count_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='body',
            new_name='comment',
        ),
    ]
