# Generated by Django 5.2.5 on 2025-08-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productoffer',
            constraint=models.UniqueConstraint(fields=('product',), name='unique_product_offer'),
        ),
    ]
