# Generated by Django 5.2.5 on 2025-09-11 07:26

import cloudinary.models
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productoffer_unique_product_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='product'),
            preserve_default=False,
        ),
    ]
